#!/usr/bin/env python3

import argparse
import os


parser = argparse.ArgumentParser()
parser.add_argument('directory', type=str, help='directory to process')
args = parser.parse_args()

directory = os.path.abspath(args.directory)

assert os.path.isdir(directory)
assert os.path.basename(directory) == 'scoop'

path = '{}\\shims'.format(directory)
prefix = 'path = '

for shim in os.listdir(path):
    if shim.endswith('.shim'):
        full = os.path.join(path, shim)
        with open(full, 'r', encoding='utf-8-sig') as f:
            content = f.read()
        print(content)
        if content.startswith(prefix):
            print(full)
            index = content.find('\\scoop\\apps')
            content = prefix + os.path.dirname(directory) + content[index:]
            with open(full, 'w') as f:
                f.write(content)
