#!/usr/bin/env python3

import argparse
import os
import shutil


parser = argparse.ArgumentParser()
parser.add_argument('directory', type=str, help='directory to process')
parser.add_argument('--relative-shims', action='store_true', help='make shims relative')
args = parser.parse_args()

directory = os.path.abspath(args.directory)

assert os.path.isdir(directory)
assert os.path.basename(directory) == 'scoop'

path = '{}\\shims'.format(directory)
prefix = 'path = '

shimexe = 'scoop/supporting/shimexe/bin/shim.exe'
if args.relative_shims:
    assert os.path.isfile(shimexe)

for shim in os.listdir(path):
    if shim.endswith('.shim'):
        full = os.path.join(path, shim)
        with open(full, 'r', encoding='utf-8-sig') as f:
            content = f.read()
        print(content)
        if content.startswith(prefix):
            print(full)
            index = content.find('\\scoop\\apps')
            if args.relative_shims:
                new_directory = "..\\.."
                shutil.copyfile(shimexe, os.path.splitext(full)[0] + '.exe')
            else:
                new_directory = os.path.dirname(directory)
            content = prefix + new_directory + content[index:]
            with open(full, 'w') as f:
                f.write(content)
